sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
python:
  - "2.7"
notifications:
  email: false
  slack: 353swe:TBr27Dyzfxr9mmz1qYaWjJiv
cache:
  directories:
    - node_modules
env:
  global:
    - NODE_ENV=development
jobs:
  include:
    - stage: test
      install: npm install
      before_script:
        - npm run testrpc
        - npm run compile
        - npm run eslint
      script:
        - npm run test
        - npm run soltest
    - stage: code-coverage
      if: branch = master
      before_script: npm run rpcov
      install:
        - sudo apt-get install python-pip python-dev
        - sudo pip install bs4
        - sudo pip install unirest
      script:
       - python scripts/js-coverage.py
       - python scripts/solidity-coverage.py
      after_success:
       - npm run merge-coverage
       - cat report.lcov | COVERALLS_REPO_TOKEN=$repo_token COVERALLS_SERVICE_NAME=travis-pro ./node_modules/.bin/coveralls
    - stage: deploy-to-production
      if: branch = master
      script:
        - npm run build-prod
      deploy:
        provider: surge
        project: ./dist/
        domain: marvin.surge.sh
        skip_cleanup: true
