export const universityAction = {
  GET_ADMIN_NUMBER: 'GET_ADMIN_NUMBER',
  RETURN_ADMIN_NUMBER: 'RETURN_ADMIN_NUMBER',
  ADD_NEW_ADMIN: 'ADD_NEW_ADMIN',
  GET_ALL_ADMINS: 'GET_ALL_ADMINS',
  RETURN_ALL_ADMINS: 'RETURN_ALL_ADMINS',
};

export const userAction = {
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_UPDATED: 'USER_UPDATED',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',
  USER_TRY_LOGIN: 'USER_TRY_LOGIN',
  METAMASK: 'METAMASK',
  EDIT_ADDRESS: 'EDIT_ADDRESS',
};
